service:
  name: sls-04-s3

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-2
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:ListBucket"
         - "s3:GetObject"
         - "s3:PutObject"
       Resource: "arn:aws:s3:::sls-04-s3/*"

functions:
  first:
    handler: first.hello

resources:
  Resources:
    FirstLambdaPermissionS3:
      Type: "AWS::Lambda::Permission"
      Properties:
        FunctionName:
          "Fn::GetAtt":
            - FirstLambdaFunction
            - Arn
        Principal: "s3.amazonaws.com"
        Action: "lambda:InvokeFunction"
        SourceAccount:
          Ref: AWS::AccountId
        SourceArn: "arn:aws:s3:::sls-04-s3"
